// const newCategory = (item: Icategory[]) => {
//   localStorage.setItem("products", JSON.stringify(item));
// };

// const newData: Iproduct[] = [
//   {
//     id: 1,
//     image: "",
//     thumbnail: "",
//     category_id: 1,
//     category: "맛있는 빵",
//     order: 1,
//     type_id: 1,
//     type: "빵",
//     name: "펭귄 빵",
//     represent: true,
//     popular: false,
//     price: 1000,
//     status_code: 1,
//     status: "판매중",
//     create_at: "",
//     modified_at: "",
//     sal_record: 0,
//     description: "맛있는 펭귄모양의 빵입니다.",
//   },

//   {
//     id: 2,
//     image: "",
//     thumbnail: "",
//     category_id: 2,
//     category: "건강한 샐러드",
//     order: 1,
//     type_id: 2,
//     type: "샐러드",
//     name: "남극 이끼 샐러드",
//     represent: true,
//     popular: true,
//     price: 2000,
//     status_code: 1,
//     status: "판매중",
//     create_at: "",
//     modified_at: "",
//     sal_record: 0,
//     description: "상당히 식감이 좋은 이끼 샐러드입니다.",
//   },
//   {
//     id: 3,
//     image: "",
//     thumbnail: "",
//     category_id: 3,
//     category: "신선한 우유",
//     order: 1,
//     type_id: 3,
//     type: "우유",
//     name: "북극 우유",
//     represent: true,
//     popular: false,
//     price: 3000,
//     status_code: 1,
//     status: "판매중",
//     create_at: "",
//     modified_at: "",
//     sal_record: 0,
//     description: "북극까지 갔다와서 파는 우유입니다.",
//   },
// ];

export default test;
